FROM python:3

COPY . .

RUN pip install django
RUN pip install psycopg2-binary
RUN pip install django-grappelli
RUN pip install pytest-django

RUN python3 manage.py collectstatic

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait

RUN chmod +x ./script_test.sh
RUN chmod +x ./wait

CMD /wait && ./script_test.sh