version: "3"
services:
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile_test
    container_name: news_portal
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "test@gmail.com"
      DJANGO_SUPERUSER_PASSWORD: "admin"
      WAIT_HOSTS: postgres:5432