# Generated by Django 4.1.1 on 2022-10-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("insert into news_news (title, text, pub_date, author) values ('Lorem Ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies dictum nibh. Aenean eget elit elit. Integer sit amet tellus quis eros pellentesque semper vitae at risus. Aliquam eget odio nunc. Nunc bibendum tincidunt elementum. Suspendisse a mauris suscipit, laoreet enim vel, hendrerit nulla. Pellentesque tristique quam non semper semper.Donec a posuere nisl. Sed sapien massa, blandit sed dignissim tristique, egestas non nisl. Proin non nunc id quam sagittis imperdiet sed sed urna. Suspendisse pulvinar vel orci nec condimentum. Proin volutpat fermentum dictum. In posuere at elit tristique pretium. Sed eget lectus sit amet risus commodo congue. Vivamus vehicula semper libero quis sagittis. Pellentesque ut ultrices odio, ut commodo urna. Quisque varius suscipit luctus. Cras commodo vehicula dapibus. In in tempor mi, non feugiat eros. In a diam urna. Duis at felis lectus. Nam auctor viverra nisl quis faucibus.', 'now()', 'John Doe')"),
        migrations.RunSQL("insert into news_news (title, text, pub_date, author) values ('Suspendisse potenti.', 'Curabitur ullamcorper quam et nibh scelerisque, id faucibus quam hendrerit. Praesent sagittis, lorem mattis semper egestas, dolor mi scelerisque tortor, sit amet pretium nisi leo eget magna. Nulla facilisi. Sed eu eleifend lorem. Cras nec nunc ut urna pretium suscipit. Fusce non dictum mauris. Vivamus vitae tristique nisl. Aenean sollicitudin pretium arcu, scelerisque interdum purus fringilla in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed at fermentum magna. In rhoncus tempus turpis, in euismod eros porttitor eu. Nam eu dui accumsan, cursus sem ut, faucibus diam. Aenean eu velit eget felis molestie dapibus. Suspendisse accumsan ultrices turpis vitae mattis.', 'now()', 'Jane Doe')")
    ]
